ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '070078';
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '070078';
CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '070078';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;