services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    command: start-dev
    ports:
      - "127.0.0.1:7001:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME=sso.anla.my.id
    restart: unless-stopped
    volumes:
      - ./providers:/opt/keycloak/providers
    networks:
      - default
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`sso.anla.my.id`)"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=coolify"

networks:
  coolify:
    name: coolify
    external: true
